{% set name = "fst-pso" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fst-pso-{{ version }}.tar.gz
  sha256: b3d16ec27b0b4d36b35b306af40c00cd0b34e5e0a9e30a71ed02490e8954a26a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - miniful

test:
  imports:
    - fstpso
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aresio/fst-pso
  summary: Fuzzy Self-Tuning PSO global optimization library
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
